### ISSUE TITLE
struct allocation in initialization

### ISSUE THREAD

**Issue by seppo0010** [twitter/ccommon#16]
I noticed this asymmetry among different modules, and I was wondering if there's a reason for it or we should unify them. On some cases, the struct calls `cc_alloc` and returns a pointer to the newly created struct[1], and in other cases, it receives a pointer to a memory address to use that has not yet being initialized[2]. The latter seems to be more generic, because it allows to be used with stack allocations.

[1] https://github.com/twitter/ccommon/blob/master/src/cc_log.c#L76
[2] https://github.com/twitter/ccommon/blob/master/include/cc_bstring.h#L52

**Comment by thinkingfish** [comment]
I think there will be a need for both, and we should clarify the naming (current naming is fine, just need to explicitly state the rule). Let me explain these two points.

There are cases where we are using forward declaration or want to use forward declaration- usually to have multiple, sometimes platform-dependent implementations which conform to the same function signature.
In this case, allocating on the stack is not possible, since the exact size of the struct is unknown, and compiler will complain for any such allocation attempt.

That's why we have two operations: `*_create/destroy` will use allocation on heap, and deal with pointers; `*_init` only initializes the object. It is usually the case that `*_init` will be called from within `*_create` to setup the members properly. We will need to state that as a pattern we use.
