### ISSUE TITLE
Remove bool from structs

### ISSUE THREAD

**Issue by seppo0010** [twitter/ccommon#56]
According to the guidelines, we should be using `unsigned v:1` instead[1]. At least one found in include/buffer/cc_buf.h, search for others and replace all of them.

[1] https://github.com/twitter/ccommon/blob/master/docs/c-styleguide.txt#L19-L23

**Comment by thinkingfish** [comment]
I think the reason for this rule is because there's no well-defined size for the `bool` or `_Bool` (defined by C99 which `bool` expands to) types, therefore when one wants to pack or align struct members, it is hard know exactly what happens on different platforms with different compilers (since it sometimes gets defined as native `int`). On the other hand, this rule hurts readability- a boolean type is much clearer than an int type in what it means.

I read a few pages online (e.g. [this one](http://stackoverflow.com/questions/10630080/if-bool-is-a-macro-for-int-why-is-it-a-different-size)) and verified that gcc/clang/icc/msvc all have built-in support of `_Bool` as a one byte int.
So I'm reluctant to always apply this rule such as when we don't care about packing the struct (e.g. alignment or memory is not an issue)

**Comment by thinkingfish** [comment]
http://stackoverflow.com/questions/10630080/if-bool-is-a-macro-for-int-why-is-it-a-different-size

**Comment by thinkingfish** [comment]
sorry, closed by accident.

**Comment by thinkingfish** [comment]
@seppo0010 Sure. Do you want to update the style guide or should I do it?
